### ISSUE TITLE
A bit unsure how to begin

### ISSUE THREAD

**Issue by Prodiona** [FBartos/zcurve#5]
Hi devs
I like your package and am looking to use it in my upcoming thesis
However, I have no experience with R or anything. I was wondering if you knew of a guide or something?

I have downloaded the package, I can run the arguments from your README file, but I am unsure how I should input the data I have collected. In csv? 

I hope you can help
Dio

**Comment by FBartos** [comment]
Hi Dio,

I'm happy that you are interested in z-curve and getting into the R universe. 

To read data from .csv to your R session
- you need to make sure that your .csv file is in your working directory (you can check the location of your working directory with the ```getwd()``` command)
- use ```df <- read.csv(file = "your file.csv", header  = TRUE)``` (assuming that the first row contains column names)

This basically creates a data.frame called "df" that contains data from your .csv. You can then access the individual columns with '$' sign. So, assuming that the first column of your .csv contains the z-statistics and is called "z", you can access it with ```df$z```.

In order to fit a z-curve to the z-statistic, you can continue with the README file with:
```
fit <- zcurve(z = df$z)
```

Otherwise, for general R related questions, StackOverflow is usually a great source: https://stackoverflow.com/questions/tagged/r or https://www.datacamp.com/courses/free-introduction-to-r can be a good place to start learning a bit more about R.

Cheers,
Frantisek

**Comment by Prodiona** [comment]
Thank you very much, that was exactly what I was looking for.

Kind regards,
Dio

**Comment by Prodiona** [comment]
Hi again. I apologise for writing to you again.

It keeps saying - Wrong z-scores input: Data are not nummeric. - I use european excel and are writing the z-scores "2,33" and then a different z score in the next row. I've done write.csv2, but it still wont work. I couldn't find anything about this on the site you posted, unfortunenately.

Dio

**Comment by FBartos** [comment]
You can try using ```sep = ";"``` and ```dec = ","``` arguments as outlined [here](https://stackoverflow.com/questions/6123378/how-to-read-in-numbers-with-a-comma-as-decimal-separator). If that doesn't work, just shoot me a mail at f.bartos96@gmail.com with the first few rows of the file and I will see what's the problem.

Best,
Frantisek
